---
apiVersion: v1
kind: Template
labels:
  template: "${REPO_NAME}-backend-template"
metadata:
  name: "${REPO_NAME}-backend-dc"
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: "${REPO_NAME}-backend"
        app.kubernetes.io/part-of: GRAD-ADMIN
        app.openshift.io/runtime: nodejs
      name: "${REPO_NAME}-backend-dc"
    spec:
      replicas: 1
      revisionHistoryLimit: 1
      triggers: []
      selector:
        app: "${REPO_NAME}-backend"
        deploymentConfig: "${REPO_NAME}-backend-dc"
      strategy:
        resources: {}
        type: Rolling
      template:
        metadata:
          labels:
            app: "${REPO_NAME}-backend"
            deploymentConfig: "${REPO_NAME}-backend-dc"
        spec:
          containers:
            - image: image-registry.openshift-image-registry.svc:5000/bbe4c3-tools/${REPO_NAME}-backend:${TAG_NAME}
              imagePullPolicy: Always
              name: "${REPO_NAME}-backend"
              ports:
                - containerPort: ${{CONTAINER_PORT}}
                  protocol: TCP
              envFrom:
                - configMapRef:
                    name: educ-grad-admin-backend-config-map
              resources: {}
      test: false
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: "${REPO_NAME}-backend"
      name: "${REPO_NAME}-backend"
    spec:
      ports:
        - name: ${CONTAINER_PORT}-tcp
          port: ${{CONTAINER_PORT}}
          protocol: TCP
      selector:
        app: "${REPO_NAME}-backend"
        deploymentconfig: "${REPO_NAME}-backend-dc"
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: "${REPO_NAME}-backend"
      name: "${REPO_NAME}-backend"
      annotations:
        haproxy.router.openshift.io/timeout: 600s
    spec:
      host: "${HOST_ROUTE}"
      path: ${HOST_PATH}
      port:
        targetPort: ${CONTAINER_PORT}-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: "${REPO_NAME}-backend"
        weight: 100
      wildcardPolicy: None
parameters:
  - name: REPO_NAME
    description: Application repository name
    required: true
  - name: TAG_NAME
    description: Imagestream tag name
    required: false
    value: latest
  - name: HOST_ROUTE
    description: The host the route will use to expose service outside cluster
    required: true
  - name: CONTAINER_PORT
    description: The port on which the application will be accessible
    required: false
    value: "8080"
  - name: HOST_PATH
    description: The path appended to the HOST_ROUTE where the root of this project will be served
    required: false
    value: "/"
