---
apiVersion: v1
kind: Template
labels:
  template: "${REPO_NAME}-backend-template"
metadata:
  name: "${REPO_NAME}-backend-bc"
  creationTimestamp:
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp:
      labels:
        build: "${REPO_NAME}-backend"
      name: "${REPO_NAME}-backend"
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp:
      labels:
        build: "${REPO_NAME}-backend"
      name: "${REPO_NAME}-backend"
    spec:
      completionDeadlineSeconds: 900
      successfulBuildsHistoryLimit: 3
      failedBuildsHistoryLimit: 3
      nodeSelector:
      output:
        to:
          kind: ImageStreamTag
          name: "${REPO_NAME}-backend:latest"
      postCommit: {}
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi
      runPolicy: SerialLatestOnly
      source:
        contextDir: backend
        git:
          ref: "${SOURCE_REPO_REF}"
          uri: "${SOURCE_REPO_URL}"
        type: Git
      strategy:
        dockerStrategy:
          pullSecret:
            name: artifactory-creds
          env:
            - name: BUILD_LOGLEVEL
              value: '2'
            - name: NPM_CONFIG_LOGLEVEL
              value: notice
        type: Docker
parameters:
  - name: REPO_NAME
    description: Application repository name
    required: true
  - name: SOURCE_REPO_REF
    description: Git Pull Request Reference (i.e. 'pull/CHANGE_ID/head')
    required: true
  - name: SOURCE_REPO_URL
    description: Git Repository URL
    required: true
