name: Daily Regression - DEV
on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1-5'

jobs:
  DailyRegression:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: test
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - run: npm install
      - run: npm run daily-regression
        if: ${{ always() }}
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          TEST_ADMIN_USERNAME: ${{ secrets.TEST_ADMIN_USERNAME }}
          TEST_ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}
          TEST_PEN: ${{ secrets.TEST_PEN }}
          API_HTML_STATUS_CLASS_THRESHOLD: 399
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET: ${{ secrets.TOKEN_CLIENT_SECRET }}
          TOKEN_ENDPOINT: ${{ secrets.TOKEN_ENDPOINT }}
      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "Grad Daily Regression - DEV --->"
          icon_emoji: ":bell:"
          channel: "grad-project"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK_FAILURES }}

