name: Daily Regression - DEV (SH Runners)
on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 11 * * 1-5'

env:
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  RUNNER_DEPLOYMENT_NAMESPACE: ${{ secrets.RUNNER_DEPLOYMENT_NAMESPACE }}
  GITHUB_REPO: ${{ github.event.repository.name }}
  ORGANIZATION: bcgov
  GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  DeployRunner:
    runs-on: ubuntu-20.04
    outputs:
      runner_name: ${{ steps.deploy_runner.outputs.runner_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4
      - uses: ./.github/actions/deploy-os-runner
        id: deploy_runner
        with:
          runner-deployment-namespace: ${{ env.RUNNER_DEPLOYMENT_NAMESPACE }}
          openshift-token: ${{ env.OPENSHIFT_TOKEN }}
          openshift-server: ${{ env.OPENSHIFT_SERVER }}
          github-repo: ${{ env.GITHUB_REPO }}
          gh-access-token: ${{ env.GITHUB_ACCESS_TOKEN }}
          secret-ref: test-runner-dev-secrets
  # run test on the github runner
  DailyRegression:
    runs-on: ${{ needs.DeployRunner.outputs.runner_name }}
    environment: dev
    needs: [DeployRunner]
    defaults:
      run:
        working-directory: test
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - run: npm install
      - run: npm run daily-regression
        if: ${{ always() }}
        env:
          #BASE_URL: ${{ secrets.BASE_URL }}
          TEST_ADMIN_USERNAME: ${{ secrets.TEST_ADMIN_USERNAME }}
          TEST_ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}
          #TEST_PEN: ${{ secrets.TEST_PEN }}
          #API_HTML_STATUS_CLASS_THRESHOLD: 399
          #TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          #TOKEN_CLIENT_SECRET: ${{ secrets.TOKEN_CLIENT_SECRET }}
          #TOKEN_ENDPOINT: ${{ secrets.TOKEN_ENDPOINT }}
      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "Grad Daily Regression - DEV --->"
          icon_emoji: ":bell:"
          channel: "grad-project"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK_FAILURES }}
  # now burn it all down!!
  TearDown:
    runs-on: ubuntu-20.04
    if: ${{ always() }}
    needs: [DeployRunner, DailyRegression]
    steps:
      - uses: actions/checkout@v3
      - uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4
      - uses: ./.github/actions/teardown-os-runner
        with:
          runner-deployment-namespace: ${{ env.RUNNER_DEPLOYMENT_NAMESPACE }}
          runner-deployment-name: ${{ needs.DeployRunner.outputs.runner_name }}
          openshift-token: ${{ env.OPENSHIFT_TOKEN }}
          openshift-server: ${{ env.OPENSHIFT_SERVER }}

